In [9]:
import numpy as np
def left(initial_state):
    for i in range(0,3):
      for j in range(0,3):
        if (initial_state[i][j]==0) :
          if j>0:
            initial_state[i][j-1]= initial_state[i][j-1] + initial_state[i][j] # a = a+b b = a-b a= a-b
            initial_state[i][j]= initial_state[i][j-1] - initial_state[i][j]
            initial_state[i][j-1]=initial_state[i][j-1] - initial_state[i][j]
            return(initial_state)
          else:
            print("error")
def right(initial_state):
  for i in range(0,3):
    for j in range(0,3):
      if (initial_state[i][j]==0):
        if j<2:
          initial_state[i][j+1] = initial_state[i][j+1] + initial_state[i][j]
          initial_state[i][j]= initial_state[i][j+1] - initial_state[i][j]
          initial_state[i][j+1]= initial_state[i][j+1] - initial_state[i][j]
          return(initial_state) 
        else:
          print("error")
def up(initial_state):
    for i in range(0,3):
      for j in range(0,3):
        if (initial_state[i][j]==0) :
          if i>0:
            initial_state[i-1][j] = initial_state[i-1][j] + initial_state[i][j] 
            initial_state[i][j]=initial_state[i-1][j] - initial_state[i][j]
            initial_state[i-1][j] = initial_state[i-1][j] - initial_state[i][j]
            return (initial_state)
          else:
            print("error")
def down(initial_state):
    for i in range(0,3):
      for j in range(0,3):
        if (initial_state[i][j]==0):
          if i<2:
            initial_state[i+1][j] = initial_state[i+1][j] + initial_state[i][j]
            initial_state[i][j]=initial_state[i+1][j] - initial_state[i][j]
            initial_state[i+1][j]=initial_state[i+1][j] - initial_state[i][j]
            return (initial_state)  
          else:
            print("error")
#main
temp=0
print("Enter a initial state(with spaces)::{eg:- 1 2 3 4 5 6 7 8 0}")
initial_state=[int(i) for i in input().split()]
initial_state= np.array([initial_state]).reshape(3,3)
print("Given input is::")
print(initial_state)
a=int(input("Enter 1 for up, 2 for down, 3 for left and 4 for right:: "))
print("Output:")
if a==1:
  print(up(initial_state))
elif a==2:
  print(down(initial_state))
elif a==3:
  print(left(initial_state))
elif a==4:
  print(right(initial_state))
else:
  print("give a valid input")


Enter a initial state(with spaces)::{eg:- 1 2 3 4 5 6 7 8 0}
0 1 2 3 4 5 6 7 8
Given input is::
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Enter 1 for up, 2 for down, 3 for left and 4 for right:: 2
Output:
[[3 1 2]
 [0 4 5]
 [6 7 8]]
