In [96]:
import numpy as np
class MyNode():
    def __init__(self,s,p_node,move,depth,step_cost,path_cost):
        self.s = s
        self.p_node = p_node
        self.move = move
        self.depth = depth
        self.step_cost = step_cost
        self.path_cost = path_cost
        self.move_up = None
        self.move_left = None
        self.move_right = None
        self.move_down = None
    
    def try_down(self):
        z_index = [i[0] for i in np.where(self.s==0)]
        if z_index[0] == 0:
            return False
        else:
            u_value = self.s[z_index[0]-1,z_index[1]]
            new_s = self.s.copy()
            new_s[z_index[0],z_index[1]] = u_value
            new_s[z_index[0]-1,z_index[1]]= 0
            return new_s,u_value
    
    def try_right(self):
        z_index = [i[0] for i in np.where(self.s==0)]
        if z_index[1] == 0:
            return False
        else:
            l_value = self.s[z_index[0],z_index[1]-1]
            new_s = self.s.copy()
            new_s[z_index[0],z_index[1]] = l_value
            new_s[z_index[0],z_index[1]-1]= 0
            return new_s,l_value
    
    def try_left(self):
        z_index = [i[0] for i in np.where(self.s==0)]
        if z_index[1] == 2:
            return False
        else:
            r_value = self.s[z_index[0],z_index[1]+1]
            new_s = self.s.copy()
            new_s[z_index[0],z_index[1]] = r_value
            new_s[z_index[0],z_index[1]+1]= 0
            return new_s,r_value
        
    def try_up(self):
        z_index = [i[0] for i in np.where(self.s==0)]
        if z_index[0] == 2:
            return False
        else:
            d_value = self.s[z_index[0]+1,z_index[1]]
            new_s = self.s.copy()
            new_s[z_index[0],z_index[1]] = d_value
            new_s[z_index[0] +1,z_index[1]]= 0
            return new_s,d_value

    def path(self):
        s_trace=[self.s]
        move_trace=[self.move]
        depth_trace=[self.depth]
        step_cost_trace = [self.step_cost]
        path_cost_trace = [self.path_cost]
        while self.p_node:
            self = self.p_node
            s_trace.append(self.s)
            move_trace.append(self.move)
            depth_trace.append(self.depth)
            step_cost_trace.append(self.step_cost)
            path_cost_trace.append(self.path_cost)
        step_counter=0
        while s_trace:
            print ('step',step_counter)
            print( s_trace.pop())
            print("action=" ,move_trace.pop(),",depth=", str(depth_trace.pop()),", step cost=" , str(step_cost_trace.pop())," total cost=", str(path_cost_trace.pop()))
            step_counter +=1
                    
    def UCS(self,goal_s):
      queue=[(self,0)]
      queue_num_nodes_popped = 0
      queue_max_length = 1
      depth_queue = [(0,0)]
      path_cost_queue = [0]
      visited = set([])

      while queue:
        queue = sorted(queue,key=lambda x:x[1])
        depth_queue = sorted(depth_queue, key=lambda x:x[1])
        path_cost_queue = sorted(path_cost_queue, key=lambda x:x)
        
        if len(queue) > queue_max_length:
              queue_max_length = len(queue)
        current_node = queue.pop(0)[0]
        queue_num_nodes_popped +=1
        current_depth = depth_queue.pop(0)[0]
        current_path_cost = path_cost_queue.pop(0)
        visited.add(tuple(current_node.s.reshape(1,9)[0])) 
        if np.array_equal(current_node.s, goal_s):
              current_node.path()
              return True
        else:
              if current_node.try_down():
                  new_s,u_value = current_node.try_down()
                  if tuple(new_s.reshape(1,9)[0]) not in visited:
                    current_node.move_down = MyNode(s=new_s, p_node=current_node,move='up',depth=current_depth+1,step_cost=u_value, path_cost=current_path_cost + u_value+down_cost)
                    queue.append((current_node.move_down,current_path_cost+u_value))
                    depth_queue.append((current_depth+1,current_path_cost+u_value))
                    path_cost_queue.append(current_path_cost+u_value+down_cost)
              if current_node.try_right():
                    new_s,l_value = current_node.try_right()
                    if tuple(new_s.reshape(1,9)[0]) not in visited:
                      current_node.move_right = MyNode(s=new_s, p_node=current_node,move='left',depth=current_depth+1,step_cost=l_value, path_cost=current_path_cost + l_value+ right_cost)
                      queue.append((current_node.move_right,current_path_cost+l_value))
                      depth_queue.append((current_depth+1,current_path_cost+l_value))
                      path_cost_queue.append(current_path_cost+l_value+right_cost)
              if current_node.try_left():
                    new_s,r_value = current_node.try_left()
                    if tuple(new_s.reshape(1,9)[0]) not in visited:
                      current_node.move_left = MyNode(s=new_s, p_node=current_node,move='right',depth=current_depth+1,step_cost=r_value, path_cost=current_path_cost + r_value+left_cost)
                      queue.append((current_node.move_left,current_path_cost+r_value))
                      depth_queue.append((current_depth+1,current_path_cost+r_value))
                      path_cost_queue.append(current_path_cost+r_value+left_cost)
              if current_node.try_up():
                    new_s,d_value = current_node.try_up()
                    if tuple(new_s.reshape(1,9)[0]) not in visited:
                      current_node.move_up = MyNode(s=new_s, p_node=current_node,move='down',depth=current_depth+1,step_cost=d_value, path_cost=current_path_cost + d_value+up_cost)
                      queue.append((current_node.move_up,current_path_cost+d_value))
                      depth_queue.append((current_depth+1,current_path_cost+d_value))
                      path_cost_queue.append(current_path_cost+d_value+up_cost)
          


In [97]:
initial_s = np.array([1,3,4,8,6,2,7,0,5]).reshape(3,3)
goal_s = np.array([1,2,3,8,0,4,7,6,5]).reshape(3,3)
up_cost=1
right_cost=1
left_cost=1
down_cost=1
root_node = MyNode(s= initial_s,p_node=None,move=None,depth=0,step_cost=0,path_cost=0)
root_node.UCS(goal_s)

step 0
[[1 3 4]
 [8 6 2]
 [7 0 5]]
action= None ,depth= 0 , step cost= 0  total cost= 0
step 1
[[1 3 4]
 [8 0 2]
 [7 6 5]]
action= up ,depth= 1 , step cost= 6  total cost= 7
step 2
[[1 3 4]
 [8 2 0]
 [7 6 5]]
action= right ,depth= 2 , step cost= 2  total cost= 10
step 3
[[1 3 0]
 [8 2 4]
 [7 6 5]]
action= up ,depth= 3 , step cost= 4  total cost= 15
step 4
[[1 0 3]
 [8 2 4]
 [7 6 5]]
action= left ,depth= 4 , step cost= 3  total cost= 19
step 5
[[1 2 3]
 [8 0 4]
 [7 6 5]]
action= down ,depth= 5 , step cost= 2  total cost= 22
27
19


True

In [98]:
up_cost=1
right_cost=0.5
left_cost=2
down_cost=1
root_node.UCS(goal_s)

step 0
[[1 3 4]
 [8 6 2]
 [7 0 5]]
action= None ,depth= 0 , step cost= 0  total cost= 0
step 1
[[1 3 4]
 [8 0 2]
 [7 6 5]]
action= up ,depth= 1 , step cost= 6  total cost= 7
step 2
[[1 3 4]
 [8 2 0]
 [7 6 5]]
action= right ,depth= 2 , step cost= 2  total cost= 11
step 3
[[1 3 0]
 [8 2 4]
 [7 6 5]]
action= up ,depth= 3 , step cost= 4  total cost= 16
step 4
[[1 0 3]
 [8 2 4]
 [7 6 5]]
action= left ,depth= 4 , step cost= 3  total cost= 19.5
step 5
[[1 2 3]
 [8 0 4]
 [7 6 5]]
action= down ,depth= 5 , step cost= 2  total cost= 22.5
27
19


True