In [1]:
#import statements
import time
import numpy as np


In [2]:
class Node():
    def __init__(self,state,parent,action,depth,step_cost,path_cost,heuristic_cost):
        self.state = state
        self.parent = parent
        self.action = action
        self.depth = depth
        self.step_cost = step_cost
        self.path_cost = path_cost
        self.heuristic_cost = heuristic_cost
        self.move_up = None
        self.move_left = None
        self.move_right = None
        self.move_down = None
    
    def try_move_down(self):
        zero_index = [i[0] for i in np.where(self.state==0)]
        if zero_index[0] == 0:
            return False
        else:
            up_value = self.state[zero_index[0]-1,zero_index[1]]
            new_state = self.state.copy()
            new_state[zero_index[0],zero_index[1]] = up_value
            new_state[zero_index[0]-1,zero_index[1]]= 0
            return new_state,up_value
    
    def try_move_right(self):
        zero_index = [i[0] for i in np.where(self.state==0)]
        if zero_index[1] == 0:
            return False
        else:
            left_value = self.state[zero_index[0],zero_index[1]-1]
            new_state = self.state.copy()
            new_state[zero_index[0],zero_index[1]] = left_value
            new_state[zero_index[0],zero_index[1]-1]= 0
            return new_state,left_value
    
    def try_move_left(self):
        zero_index = [i[0] for i in np.where(self.state==0)]
        if zero_index[1] == 2:
            return False
        else:
            right_value = self.state[zero_index[0],zero_index[1]+1]
            new_state = self.state.copy()
            new_state[zero_index[0],zero_index[1]] = right_value
            new_state[zero_index[0],zero_index[1]+1]= 0
            return new_state,right_value
        
    def try_move_up(self):
        zero_index = [i[0] for i in np.where(self.state==0)]
        if zero_index[0] == 2:
            return False
        else:
            lower_value = self.state[zero_index[0]+1,zero_index[1]]
            new_state = self.state.copy()
            new_state[zero_index[0],zero_index[1]] = lower_value
            new_state[zero_index[0] +1,zero_index[1]]= 0
            return new_state,lower_value

    

    def print_path(self):
        state_trace=[self.state]
        action_trace=[self.action]
        depth_trace=[self.depth]
        step_cost_trace = [self.step_cost]
        path_cost_trace = [self.path_cost]
        while self.parent:
            self = self.parent
            state_trace.append(self.state)
            action_trace.append(self.action)
            depth_trace.append(self.depth)
            step_cost_trace.append(self.step_cost)
            path_cost_trace.append(self.path_cost)
        step_counter=0
        while state_trace:
            print ('step',step_counter)
            print( state_trace.pop())
            print("action=" ,action_trace.pop(),",depth=", str(depth_trace.pop()),", step cost=" , str(step_cost_trace.pop()),", total cost=", str(path_cost_trace.pop()))
            step_counter +=1
    def BFS(self,goal_state):
        start = time.time()
        queue = [self] 
        queue_num_nodes_popped = 0
        queue_max_length = 1
        depth_queue = [0]
        path_cost_queue = [0]
        visited = set([])
        
        while queue:
            if len(queue) > queue_max_length:
                  queue_max_length = len(queue)
            current_node = queue.pop(0)
            queue_num_nodes_popped += 1
            current_depth = depth_queue.pop(0)
            current_path_cost = path_cost_queue.pop(0)
            visited.add(tuple(current_node.state.reshape(1,9)[0]))
                
            if np.array_equal(current_node.state,goal_state):
                current_node.print_path()
                print (str(queue_num_nodes_popped))
                print (str(queue_max_length))
                return True
            else:
                if current_node.try_move_down():
                    new_state,up_value = current_node.try_move_down()
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                        current_node.move_down = Node(state=new_state,parent=current_node,action='down',depth=current_depth+1,step_cost=up_value,path_cost=current_path_cost+up_value,heuristic_cost=0)
                        queue.append(current_node.move_down)
                        depth_queue.append(current_depth+1)
                        path_cost_queue.append(current_path_cost+up_value)

                if current_node.try_move_right():
                    new_state,left_value = current_node.try_move_right()
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                        current_node.move_right = Node(state=new_state,parent=current_node,action='right',depth=current_depth+1,step_cost=left_value,path_cost=current_path_cost+left_value,heuristic_cost=0)
                        queue.append(current_node.move_right)
                        depth_queue.append(current_depth+1)
                        path_cost_queue.append(current_path_cost+left_value)

                if current_node.try_move_up():
                    new_state,lower_value = current_node.try_move_up()
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                        current_node.move_up = Node(state=new_state,parent=current_node,action='up',depth=current_depth+1,step_cost=lower_value,path_cost=current_path_cost+lower_value,heuristic_cost=0)
                        queue.append(current_node.move_up)
                        depth_queue.append(current_depth+1)
                        path_cost_queue.append(current_path_cost+lower_value)

                if current_node.try_move_left():
                    new_state,right_value = current_node.try_move_left()
                    if tuple(new_state.reshape(1,9)[0]) not in visited:
                        current_node.move_left = Node(state=new_state,parent=current_node,action='left',depth=current_depth+1,step_cost=right_value,path_cost=current_path_cost+right_value,heuristic_cost=0)
                        queue.append(current_node.move_left)
                        depth_queue.append(current_depth+1)
                        path_cost_queue.append(current_path_cost+right_value)

In [3]:
initial_state = np.array([1,3,4,8,6,2,7,0,5]).reshape(3,3)
goal_state = np.array([1,3,4,8,6,2,0,7,5]).reshape(3,3)

In [4]:
root_node = Node(state= initial_state,parent=None,action=None,depth=0,step_cost=0,path_cost=0,heuristic_cost=0)

In [5]:
root_node.BFS(goal_state)

step 0
[[1 3 4]
 [8 6 2]
 [7 0 5]]
action= None ,depth= 0 , step cost= 0 , total cost= 0
step 1
[[1 3 4]
 [8 6 2]
 [0 7 5]]
action= right ,depth= 1 , step cost= 7 , total cost= 7
3
5


True